package validate

var validatorTagMap = map[string]string{
	// Fields
	"eqcsfield":     "%s必须等于%s字段（相对）",
	"eqfield":       "%s必须等于%s字段",
	"fieldcontains": "%s必须包含指定字符",
	"fieldexcludes": "%s不能包含指定字符",
	"gtcsfield":     "%s必须大于%s字段（相对）",
	"gtecsfield":    "%s必须大于等于%s字段（相对）",
	"gtefield":      "%s必须大于等于%s字段",
	"gtfield":       "%s必须大于%s字段",
	"ltcsfield":     "%s必须小于%s字段（相对）",
	"ltecsfield":    "%s必须小于等于%s字段（相对）",
	"ltefield":      "%s必须小于等于%s字段",
	"ltfield":       "%s必须小于%s字段",
	"necsfield":     "%s不能等于%s字段（相对）",
	"nefield":       "%s不能等于%s字段",

	// Network
	"cidr":             "%s必须是合法 CIDR",
	"cidrv4":           "%s必须是合法 CIDRv4",
	"cidrv6":           "%s必须是合法 CIDRv6",
	"datauri":          "%s必须是合法 Data URI",
	"fqdn":             "%s必须是合法 FQDN",
	"hostname":         "%s必须是合法主机名 RFC 952",
	"hostname_rfc1123": "%s必须是合法主机名 RFC 1123",
	"hostname_port":    "%s必须是合法 HostPort",
	"port":             "%s必须是合法端口",
	"ip":               "%s必须是合法 IP 地址",
	"ip4_addr":         "%s必须是合法 IPv4 地址",
	"ip6_addr":         "%s必须是合法 IPv6 地址",
	"ip_addr":          "%s必须是合法 IP 地址",
	"ipv4":             "%s必须是合法 IPv4 地址",
	"ipv6":             "%s必须是合法 IPv6 地址",
	"mac":              "%s必须是合法 MAC 地址",
	"tcp4_addr":        "%s必须是合法 TCPv4 地址",
	"tcp6_addr":        "%s必须是合法 TCPv6 地址",
	"tcp_addr":         "%s必须是合法 TCP 地址",
	"udp4_addr":        "%s必须是合法 UDPv4 地址",
	"udp6_addr":        "%s必须是合法 UDPv6 地址",
	"udp_addr":         "%s必须是合法 UDP 地址",
	"unix_addr":        "%s必须是合法 Unix Socket 地址",
	"uri":              "%s必须是合法 URI",
	"url":              "%s必须是合法 URL",
	"http_url":         "%s必须是合法 HTTP URL",
	"https_url":        "%s必须是合法 HTTPS URL",
	"url_encoded":      "%s必须是 URL 编码",
	"urn_rfc2141":      "%s必须是合法 URN RFC 2141",

	// Strings
	"alpha":           "%s只能包含字母",
	"alphaspace":      "%s只能包含字母和空格",
	"alphanum":        "%s只能包含字母和数字",
	"alphanumunicode": "%s只能包含字母数字 Unicode",
	"alphaunicode":    "%s只能包含字母 Unicode",
	"ascii":           "%s必须是 ASCII 字符",
	"boolean":         "%s必须是布尔值",
	"contains":        "%s必须包含指定子串",
	"containsany":     "%s必须包含任意指定字符",
	"containsrune":    "%s必须包含指定字符",
	"endsnotwith":     "%s不能以指定子串结尾",
	"endswith":        "%s必须以指定子串结尾",
	"excludes":        "%s不能包含指定子串",
	"excludesall":     "%s不能包含任意指定字符",
	"excludesrune":    "%s不能包含指定字符",
	"lowercase":       "%s必须是小写",
	"multibyte":       "%s必须是多字节字符",
	"number":          "%s必须是数字",
	"numeric":         "%s必须是数字",
	"printascii":      "%s必须是可打印 ASCII",
	"startsnotwith":   "%s不能以指定子串开头",
	"startswith":      "%s必须以指定子串开头",
	"uppercase":       "%s必须是大写",

	// Format
	"base64":                        "%s必须是合法 Base64",
	"base64url":                     "%s必须是合法 Base64URL",
	"base64rawurl":                  "%s必须是合法 Base64RawURL",
	"bic_iso_9362_2014":             "%s必须是合法 BIC (ISO 9362:2014)",
	"bic":                           "%s必须是合法 BIC (ISO 9362:2022)",
	"bcp47_language_tag":            "%s必须是合法 BCP 47 语言标签",
	"btc_addr":                      "%s必须是合法比特币地址",
	"btc_addr_bech32":               "%s必须是合法 Bech32 地址",
	"credit_card":                   "%s必须是合法信用卡号",
	"mongodb":                       "%s必须是合法 MongoDB ObjectID",
	"mongodb_connection_string":     "%s必须是合法 MongoDB 连接字符串",
	"cron":                          "%s必须是合法 Cron 表达式",
	"spicedb":                       "%s必须是合法 SpiceDb ObjectID/Permission/Type",
	"datetime":                      "%s必须是合法日期时间",
	"e164":                          "%s必须是 E.164 电话号码",
	"ein":                           "%s必须是有效的美国雇主识别号",
	"email":                         "%s必须是合法邮箱",
	"eth_addr":                      "%s必须是合法以太坊地址",
	"hexadecimal":                   "%s必须是十六进制字符串",
	"hexcolor":                      "%s必须是十六进制颜色",
	"hsl":                           "%s必须是 HSL 字符串",
	"hsla":                          "%s必须是 HSLA 字符串",
	"html":                          "%s必须是 HTML 标签",
	"html_encoded":                  "%s必须是 HTML 编码",
	"isbn":                          "%s必须是有效 ISBN",
	"isbn10":                        "%s必须是有效 ISBN10",
	"isbn13":                        "%s必须是有效 ISBN13",
	"issn":                          "%s必须是有效 ISSN",
	"iso3166_1_alpha2":              "%s必须是 ISO 3166-1 Alpha-2 国家码",
	"iso3166_1_alpha3":              "%s必须是 ISO 3166-1 Alpha-3 国家码",
	"iso3166_1_alpha_numeric":       "%s必须是 ISO 3166-1 数字国家码",
	"iso3166_2":                     "%s必须是 ISO 3166-2 子国家码",
	"iso4217":                       "%s必须是 ISO 4217 货币码",
	"json":                          "%s必须是合法 JSON",
	"jwt":                           "%s必须是合法 JWT",
	"latitude":                      "%s必须是合法纬度",
	"longitude":                     "%s必须是合法经度",
	"luhn_checksum":                 "%s必须通过 Luhn 校验",
	"postcode_iso3166_alpha2":       "%s必须是 ISO3166 Alpha2 邮政编码",
	"postcode_iso3166_alpha2_field": "%s必须是 ISO3166 Alpha2 邮政编码字段",
	"rgb":                           "%s必须是合法 RGB 字符串",
	"rgba":                          "%s必须是合法 RGBA 字符串",
	"ssn":                           "%s必须是有效美国社会保障号",
	"timezone":                      "%s必须是合法时区",
	"uuid":                          "%s必须是合法 UUID",
	"uuid3":                         "%s必须是合法 UUID v3",
	"uuid3_rfc4122":                 "%s必须是合法 UUID v3 RFC4122",
	"uuid4":                         "%s必须是合法 UUID v4",
	"uuid4_rfc4122":                 "%s必须是合法 UUID v4 RFC4122",
	"uuid5":                         "%s必须是合法 UUID v5",
	"uuid5_rfc4122":                 "%s必须是合法 UUID v5 RFC4122",
	"uuid_rfc4122":                  "%s必须是合法 UUID RFC4122",
	"md4":                           "%s必须是 MD4 哈希",
	"md5":                           "%s必须是 MD5 哈希",
	"sha256":                        "%s必须是 SHA256 哈希",
	"sha384":                        "%s必须是 SHA384 哈希",
	"sha512":                        "%s必须是 SHA512 哈希",
	"ripemd128":                     "%s必须是 RIPEMD-128 哈希",
	"ripemd160":                     "%s必须是 RIPEMD-160 哈希",
	"tiger128":                      "%s必须是 TIGER128 哈希",
	"tiger160":                      "%s必须是 TIGER160 哈希",
	"tiger192":                      "%s必须是 TIGER192 哈希",
	"semver":                        "%s必须是合法语义化版本",
	"ulid":                          "%s必须是合法 ULID",
	"cve":                           "%s必须是有效 CVE ID",

	// Comparisons
	"eq":             "%s必须等于%s",
	"eq_ignore_case": "%s必须等于%s（忽略大小写）",
	"gt":             "%s必须大于%s",
	"gte":            "%s必须大于等于%s",
	"lt":             "%s必须小于%s",
	"lte":            "%s必须小于等于%s",
	"ne":             "%s不能等于%s",
	"ne_ignore_case": "%s不能等于%s（忽略大小写）",

	// Other
	"dir":                  "%s必须是存在的目录",
	"dirpath":              "%s必须是目录路径",
	"file":                 "%s必须是存在的文件",
	"filepath":             "%s必须是文件路径",
	"image":                "%s必须是图像",
	"isdefault":            "%s必须是默认值",
	"len":                  "%s长度必须为%s",
	"max":                  "%s长度不能大于%s",
	"min":                  "%s长度不能小于%s",
	"oneof":                "%s必须是以下值之一: %s",
	"required":             "%s不能为空",
	"required_if":          "%s在条件下不能为空",
	"required_unless":      "%s除非条件满足，否则不能为空",
	"required_with":        "%s必须与 %s 一起提供",
	"required_with_all":    "%s必须与所有 %s 一起提供",
	"required_without":     "%s在未提供 %s 时必填",
	"required_without_all": "%s在未提供任何 %s 时必填",
	"excluded_if":          "%s在条件下不允许提供",
	"excluded_unless":      "%s除非条件满足，否则不允许提供",
	"excluded_with":        "%s不允许与 %s 一起提供",
	"excluded_with_all":    "%s不允许与所有 %s 一起提供",
	"excluded_without":     "%s不允许在未提供 %s 时提供",
	"excluded_without_all": "%s不允许在未提供任何 %s 时提供",
	"unique":               "%s必须唯一",
	"validateFn":           "%s自定义验证失败",
	// Aliases
	"iscolor":      "%s必须是合法颜色 (hexcolor, rgb, rgba, hsl, hsla)",
	"country_code": "%s必须是有效国家码 (ISO3166 Alpha2 / Alpha3 / Numeric)",
}
